name: JavaScript Action

on: [push]

jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install dependencies
        run: npm install
        working-directory: .github/actions/js-action

      - name: run JavaScript Action
        id: hello
        uses: ./.github/actions/js-action
        with:
          who-to-greet: 'DevOps Engineer'

      # use the output from the 'hello' step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"