name: Test SQL Server Query

on: [push]

jobs:
  sqlserver-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SQL Server Query Action
        uses: ./.github/actions/sql-action
        with:
          db_host: 'localhost'
          db_port: '1433'
          db_user: 'sa'
          db_password: ${{ secrets.SQL_PASSWORD }}
          db_name: 'yourdbname'
          query: 'SELECT TOP 10 * FROM your_table'
